language: node_js
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
node_js:
  - "10"
cache:
  directories:
    - node_modules  
install:
  - sudo pip3 install --upgrade awscli
  - npm install -g lerna
  - npm install serverless -g
  - npm install jest -g
  - npm install eslint -g
jobs:
  include:
    - stage: "Push to Prod"
      if: branch = master AND type != pull_request
      name: "Push to Prod"
      script: "./build.sh || exit $?; ./deploy.sh || exit $?;"
      #Trigger for CI/CD To be Added srtacks separation